name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.1.0.0
          MYSQL_PORT: 3306
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: tokpa
          MYSQL_USER: root
          MYSQL_PASSWORD: 'root'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install vue
      run: npm install && npm install vue@3

    - name: Install npm dependencies
      run: npm run production

    - name: Start Mysql
      run: sudo service mysql start

    - name: Connect Mysql
      run: mysql -u root -p root

    - name: grant Mysql
      run: GRANT ALL PRIVILEGES ON tokpa.* TO 'root'@'localhost' && EXIT

    - name: Configure .env file
      run: cp .env.example .env

    - name: Run database migrations
      run: php artisan migrate --force


    - name: Generate application key
      run: php artisan key:generate

    - name: Deploy application
      run: |
        php artisan config:cache
        php artisan route:cache
