name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install vue
      run: npm install && npm install vue@3

    - name: Install npm dependencies
      run: npm run production

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1
      with:
        mysql-version: '8.0'
        mysql-root-password: '123456'
        mysql-database: tokpa
        mysql-user: root
        mysql-password: '123456'

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Configure .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Deploy application
      run: |
        php artisan config:cache
        php artisan route:cache
