name: Laravel Inertia Vue.js Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: laravel_db
        portsname: Laravel Inertia Vue.js Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Assurez-vous que ceci correspond au nom de votre secret contenant le mot de passe
          MYSQL_DATABASE: tokpa
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install npm Dependencies
      run: npm install

    - name: Build Assets
      run: npm run production

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Seed Database (if necessary)
      run: php artisan db:seed --force

    - name: Start Laravel Server
      run: php artisan serve --port=8000 &

    - name: Wait for Laravel Server to start
      run: sleep 5

    - name: Run Tests (if necessary)
      run: php artisan test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        cname: example.com # Change this to your custom domain if you have one

          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install npm Dependencies
      run: npm install

    - name: Build Assets
      run: npm run production

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Seed Database (if necessary)
      run: php artisan db:seed --force

    - name: Start Laravel Server
      run: php artisan serve --port=8000 &

    - name: Wait for Laravel Server to start
      run: sleep 5

    - name: Run Tests (if necessary)
      run: php artisan test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        cname: example.com # Change this to your custom domain if you have one
